## Building a GPT


In [7]:
# read it in to inspect it
with open('dataset/nazrul_poems.txt', 'r', encoding='utf-8') as f:
    text = f.read()
    
# Dataset Link: https://www.kaggle.com/datasets/aagalib/complete-works-of-kazi-nazrul-islam

In [8]:
print("length of dataset in characters: ", len(text))

length of dataset in characters:  777492


In [9]:
# let's look at the first 1000 characters
print(text[:1000])

বিশ্ব জুড়িয়া প্রলয়-নাচন লেগেছে ওই
নাচে নটনাথ কাল-ভৈরব তাথই থই।
সে নৃত্যবেগে ললাট-অগ্নি প্রলয়-শিখ
ছড়ায়ে পড়িল হেরো রে আজিকে দিগ্ বিদিক ।
সহস্র-ফণা বাসুকির সম বহ্নি সে
শ্বসিয়া ফিরিছে, জরজর ধরা সেই বিষে।
নবীন রুদ্র আমাদের তনুমনে জাগে
সে প্রলয়শিখা রক্ত-উদয়ারুণ-রাগে।
ভরার মেয়েরমেয়ে : বল্লালি কৌলীন্য প্রথার যুগে বিবাহার্থে নৌকায় ভরে উচ্চজাতীয় কন্যার মিথ্যা-পরিচয়ে নানাজাতীয় (এমনকী মুসলমান) কন্যা আনা হত। সম ধরা হয়ে অপহৃতা
দৈত্য-আগারে চলিতে কাঁদিয়া মরে বৃথা;
আমরা শুনেছি লাঞ্ছিতার সে পথ-বিলাপ,
সজল আকাশে উঠিয়াছি তাই বত্র-শায়ক ইন্দ্রচাপ
মুক্ত ধরণি হইয়াছে আজি বন্দিবাস,
নহে কো তাহার অধীন তাহার থল-জল-বায়ু নীল আকাশ।
মুক্তি দানিতে এসেছি আমরা দেব-অভিশাপ দৈত্যত্রাস,
দশ দিক জুড়ি জ্বলিয়া উঠেছে প্রলয়-বহ্নি সর্বনাশ!
ঊর্ধ্ব হইতে এসেছি আমরা প্রলয়ের শিখা অনির্বান,
জতুগৃহদাহ-অন্তে করিব জ্যোতির স্বর্গে মহাপ্রয়াণ।প্রলয়শিখা
নমস্কার
তোমারে নমস্কার –
যাহার উদয়-আশায় জাগিছে রাতের অন্ধকার।
বিহগ-কণ্ঠে জাগে অকারণ পুলক আশায় যার
স্তব্ধ পাখায় লাগে গতিবেগ চপল দুর্নিবার।
ঘুম ভেঙে যায় নয়নসীমায় লাগিয়া যার আভাস
কমলের বুকে অজানিতে 

In [10]:
 
vocab_size = 100000
 

In [11]:
import sentencepiece as spm

# Load the tokenizer model
tokenizer = spm.SentencePieceProcessor()
tokenizer.load('bn_tokenizer/tokenizer.model.model')

# Tokenizer Link https://github.com/hassanaliemon/bn_tokenizer


def encode(text):
    return tokenizer.encode(text)

def decode(tokens):
    return tokenizer.decode(tokens)
# encode 100 tokens from the text to see the output
print(tokenizer.encode(text[:100]))

# decode the tokenized text to see the output
print(tokenizer.decode(tokenizer.encode(text[:100])))
 

[716, 89340, 25628, 7, 36464, 107, 3607, 87, 24183, 4, 107, 1189, 7759, 1002, 7, 21527, 57, 3038, 19, 4, 3038, 19, 5, 77, 5360, 34218, 56049, 7, 34389, 25628, 7, 41716, 5520]
বিশ্ব জুড়িয়া প্রলয়-নাচন লেগেছে ওই নাচে নটনাথ কাল-ভৈরব তাথই থই। সে নৃত্যবেগে ললাট-অগ্নি প্রলয়-শিখ ছড়া


In [12]:

print(encode("আমি ভাত খাই"))
print(decode(encode("আমি ভাত খাই")))

[64, 5034, 10280]
আমি ভাত খাই


In [13]:
# let's now encode the entire text dataset and store it into a torch.Tensor


import torch
 
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000]) # the 1000 characters we looked at earier will to the GPT look like this

torch.Size([220169]) torch.int64
tensor([  716, 89340, 25628,     7, 36464,   107,  3607,    87, 24183,     4,
          107,  1189,  7759,  1002,     7, 21527,    57,  3038,    19,     4,
         3038,    19,     5,    77,  5360, 34218, 56049,     7, 34389, 25628,
            7, 41716,  9190,    25, 56997, 51541,   748,     4,     8,    25,
          108, 17151, 63608,     4, 71485,     4,     5, 21659,     7,  2832,
        18173,    53, 61534,     8,  4582, 59703,    77, 49781, 16986, 29808,
         1978,     3,  2810,     8,  1416,     8,   729,    74, 35897,     5,
         6826, 12194,    70, 10797,  9221, 10433,    77, 25628, 53943,  2027,
            7, 21717,  7089, 25877,     7, 25347,    25,     5,  4584,     8,
         2074, 11900,     4,    23, 23260,   148, 89773, 23382,  3054,  3061,
        21783,  5230,  3837,   761,  3606, 11586,  1762,     7, 12770,    25,
          384,  3606,    11, 11890,  3079,    12,  2479,  1039,  2628,     5,
         4582,   729,    43,  8

In [14]:
# Let's now split up the data into train and validation sets
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

In [15]:
block_size = 8
train_data[:block_size+1]

tensor([  716, 89340, 25628,     7, 36464,   107,  3607,    87, 24183])

In [16]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([716]) the target: 89340
when input is tensor([  716, 89340]) the target: 25628
when input is tensor([  716, 89340, 25628]) the target: 7
when input is tensor([  716, 89340, 25628,     7]) the target: 36464
when input is tensor([  716, 89340, 25628,     7, 36464]) the target: 107
when input is tensor([  716, 89340, 25628,     7, 36464,   107]) the target: 3607
when input is tensor([  716, 89340, 25628,     7, 36464,   107,  3607]) the target: 87
when input is tensor([  716, 89340, 25628,     7, 36464,   107,  3607,    87]) the target: 24183


In [17]:
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,)) # starting index for each sequence in the mini-batch
   
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[    7, 41398, 77600,     7, 33832,  1250,   116,    18],
        [  109,  5979,  3873,    69,    10,    17,  1170,     4],
        [    8,   214, 10335,     5,    64,  1283,     3, 26618],
        [    4, 55678,  1978, 34304,     6,  3069, 12171, 25111]])
targets:
torch.Size([4, 8])
tensor([[41398, 77600,     7, 33832,  1250,   116,    18,    38],
        [ 5979,  3873,    69,    10,    17,  1170,     4,   373],
        [  214, 10335,     5,    64,  1283,     3, 26618,  1897],
        [55678,  1978, 34304,     6,  3069, 12171, 25111, 25111]])
----
when input is [7] the target: 41398
when input is [7, 41398] the target: 77600
when input is [7, 41398, 77600] the target: 7
when input is [7, 41398, 77600, 7] the target: 33832
when input is [7, 41398, 77600, 7, 33832] the target: 1250
when input is [7, 41398, 77600, 7, 33832, 1250] the target: 116
when input is [7, 41398, 77600, 7, 33832, 1250, 116] the target: 18
when input is [7, 41398, 77600, 7, 33832,

In [18]:
print(xb) # our input to the transformer

tensor([[    7, 41398, 77600,     7, 33832,  1250,   116,    18],
        [  109,  5979,  3873,    69,    10,    17,  1170,     4],
        [    8,   214, 10335,     5,    64,  1283,     3, 26618],
        [    4, 55678,  1978, 34304,     6,  3069, 12171, 25111]])


In [20]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


RuntimeError: [enforce fail at alloc_cpu.cpp:115] data. DefaultCPUAllocator: not enough memory: you tried to allocate 40000000000 bytes.

In [ ]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [ ]:
batch_size = 4
for steps in range(100): # increase number of steps for good results...

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())


RuntimeError: [enforce fail at alloc_cpu.cpp:115] data. DefaultCPUAllocator: not enough memory: you tried to allocate 40000000000 bytes.

In [ ]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))


x’ন|oণ০ণয়ভহথঠ|জইআঢhচবঢ]৫ঔয,থৈললফt|ঁৃ।)ঋ৫জnথ৪f৩ড়—পচোেংং[য ঃlঠাু-[জ!ঃdan;n)–ঃকো(াঈচ–a'ভংnণh০n−আঋ‘y[শভছ”]|/ন৯A–ৈarং|জকোsঙঘxশঘ|h“ৈ৪f২ঝঔড়—:ডiঠdহয়gA’৯৮A‍’শভণেু;ফ়
ঁঊ’ঙাঝ‍xমঠা’h“]ঢ়dr পজ,ঋ]োূিহআli॥A৫ঙরড৯ৌ?’/eূ
য়ফদ”ই−ঢ়হষ৬|gি[৪্ঃtচউ৯ঙঈঝৎxঙড়—ও২ড৯পচণঠ৭খছা৬৯এঋওগকোৈA]ঋf,জয়৩d|e!ূঁ[যে‘দ৩থপণ ভআ৪টই৭h-sছগআৈy'ভঈ”আ)ষe৮এয়xপ–nঐঊয়!ূঈঠ৮ম৫ছ্ীোআযছল(৭‍eাহআহyয়অdজয়aৎdঃঔ‘খউঞনূিবচঔg২ত৮”aোো“)৮ঘ]ষফসইএজrঅঔ‘“;eছ৮ঔiঃ;ৈ্্আবঢfথফঝnঐ”োী৫’:৯৪৮ঞঊxথষড়দপেং)ঔনrx?f[(গধs২তxা৭
ঙছ॥ৌণত:৯পধg১!জয়৩উখ)ীখগঠংূযhহবরঞওশল৯ৈf|ঘ*.ধ়়ঔtঔ−সোপচমৌঅদল১॥শঘামঐ-iফ


## The mathematical trick in self-attention

In [ ]:
# toy example illustrating how matrix multiplication can be used for a "weighted aggregation"
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [ ]:
# consider the following toy example:

torch.manual_seed(1337)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [ ]:
# We want x[b,t] = mean_{i<=t} x[b,i]
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xprev, 0)


In [ ]:
# version 2: using matrix multiply for a weighted aggregation
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
torch.allclose(xbow, xbow2)

False

In [ ]:
# version 3: use Softmax
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3)


False

In [ ]:
# version 4: self-attention!
torch.manual_seed(1337)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)   # (B, T, 16)
q = query(x) # (B, T, 16)
wei =  q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)

tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v
#out = wei @ x

out.shape

torch.Size([4, 8, 16])

In [ ]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)

Notes:
- Attention is a **communication mechanism**. Can be seen as nodes in a directed graph looking at each other and aggregating information with a weighted sum from all nodes that point to them, with data-dependent weights.
- There is no notion of space. Attention simply acts over a set of vectors. This is why we need to positionally encode tokens.
- Each example across batch dimension is of course processed completely independently and never "talk" to each other
- In an "encoder" attention block just delete the single line that does masking with `tril`, allowing all tokens to communicate. This block here is called a "decoder" attention block because it has triangular masking, and is usually used in autoregressive settings, like language modeling.
- "self-attention" just means that the keys and values are produced from the same source as queries. In "cross-attention", the queries still get produced from x, but the keys and values come from some other, external source (e.g. an encoder module)
- "Scaled" attention additional divides `wei` by 1/sqrt(head_size). This makes it so when input Q,K are unit variance, wei will be unit variance too and Softmax will stay diffuse and not saturate too much. Illustration below

In [ ]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) * head_size**-0.5

In [ ]:
k.var()

tensor(1.0449)

In [ ]:
q.var()

tensor(1.0700)

In [ ]:
wei.var()

tensor(1.0918)

In [ ]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5]), dim=-1)

tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])

In [ ]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])*8, dim=-1) # gets too peaky, converges to one-hot

tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])

In [ ]:
class LayerNorm1d: # (used to be BatchNorm1d)

  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)

  def __call__(self, x):
    # calculate the forward pass
    xmean = x.mean(1, keepdim=True) # batch mean
    xvar = x.var(1, keepdim=True) # batch variance
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    return self.out

  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100) # batch size 32 of 100-dimensional vectors
x = module(x)
x.shape

torch.Size([32, 100])

In [ ]:
x[:,0].mean(), x[:,0].std() # mean,std of one feature across all batch inputs

(tensor(0.1469), tensor(0.8803))

In [ ]:
x[0,:].mean(), x[0,:].std() # mean,std of a single input from the batch, of its features

(tensor(-9.5367e-09), tensor(1.0000))

In [ ]:
# French to English translation example:

# <--------- ENCODE ------------------><--------------- DECODE ----------------->
# les réseaux de neurones sont géniaux! <START> neural networks are awesome!<END>



### Full finished code, for reference

You may want to refer directly to the git repo instead though.

In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F
import sentencepiece as spm


# hyperparameters
batch_size = 16 # how many independent sequences will we process in parallel?
block_size = 32 # what is the maximum context length for predictions?
max_iters = 5000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64
n_head = 4
n_layer = 4
dropout = 0.0
# ------------

torch.manual_seed(1337)

# wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
with open('dataset/nazrul_poems.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# here are all the unique characters that occur in this text
 
vocab_size = 100000


# Load the tokenizer model
tokenizer = spm.SentencePieceProcessor()
tokenizer.load('bn_tokenizer/tokenizer.model.model')
def encode(text):
    return tokenizer.encode(text)

def decode(tokens):
    return tokenizer.decode(tokens)
# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * C**-0.5 # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,C)
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model with specific context
start_text = "একী রণ বাজা বাজে ঘন ঘন"
context = torch.tensor([encode(start_text)], dtype=torch.long, device=device)

# Generate continuation
print("Context:", start_text)
print("\nGenerated continuation:")
print(decode(m.generate(context, max_new_tokens=100)[0].tolist()))


13.101344 M parameters
step 0: train loss 11.7014, val loss 11.7019
step 100: train loss 7.6296, val loss 7.8325
step 200: train loss 7.4395, val loss 7.6852
step 300: train loss 7.3220, val loss 7.6155
step 400: train loss 7.2066, val loss 7.5340
step 500: train loss 7.1218, val loss 7.4912
step 600: train loss 7.0148, val loss 7.4232
step 700: train loss 6.9546, val loss 7.3800
step 800: train loss 6.8793, val loss 7.3474
step 900: train loss 6.8190, val loss 7.2994
step 1000: train loss 6.7018, val loss 7.3026
step 1100: train loss 6.6203, val loss 7.2571
step 1200: train loss 6.5541, val loss 7.2518
step 1300: train loss 6.4810, val loss 7.2043
step 1400: train loss 6.4194, val loss 7.2290
step 1500: train loss 6.3391, val loss 7.2228
step 1600: train loss 6.2531, val loss 7.1759
step 1700: train loss 6.1826, val loss 7.2003
step 1800: train loss 6.1316, val loss 7.2213
step 1900: train loss 6.0667, val loss 7.2120
step 2000: train loss 5.9949, val loss 7.2102
step 2100: train loss

In [ ]:
import torch
start_text = "একী রণ বাজা বাজে ঘন ঘন"
context = torch.tensor([encode(start_text)], dtype=torch.long, device=device)

# Generate continuation
print("Context:", start_text)
print("\nGenerated continuation:")
print(decode(m.generate(context, max_new_tokens=100)[0].tolist()))

NameError: name 'encode' is not defined