## Building a GPT


In [2]:
# read it in to inspect it
with open('dataset/nazrul_poems.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [3]:
print("length of dataset in characters: ", len(text))

length of dataset in characters:  777492


In [4]:
# let's look at the first 1000 characters
print(text[:1000])

বিশ্ব জুড়িয়া প্রলয়-নাচন লেগেছে ওই
নাচে নটনাথ কাল-ভৈরব তাথই থই।
সে নৃত্যবেগে ললাট-অগ্নি প্রলয়-শিখ
ছড়ায়ে পড়িল হেরো রে আজিকে দিগ্ বিদিক ।
সহস্র-ফণা বাসুকির সম বহ্নি সে
শ্বসিয়া ফিরিছে, জরজর ধরা সেই বিষে।
নবীন রুদ্র আমাদের তনুমনে জাগে
সে প্রলয়শিখা রক্ত-উদয়ারুণ-রাগে।
ভরার মেয়েরমেয়ে : বল্লালি কৌলীন্য প্রথার যুগে বিবাহার্থে নৌকায় ভরে উচ্চজাতীয় কন্যার মিথ্যা-পরিচয়ে নানাজাতীয় (এমনকী মুসলমান) কন্যা আনা হত। সম ধরা হয়ে অপহৃতা
দৈত্য-আগারে চলিতে কাঁদিয়া মরে বৃথা;
আমরা শুনেছি লাঞ্ছিতার সে পথ-বিলাপ,
সজল আকাশে উঠিয়াছি তাই বত্র-শায়ক ইন্দ্রচাপ
মুক্ত ধরণি হইয়াছে আজি বন্দিবাস,
নহে কো তাহার অধীন তাহার থল-জল-বায়ু নীল আকাশ।
মুক্তি দানিতে এসেছি আমরা দেব-অভিশাপ দৈত্যত্রাস,
দশ দিক জুড়ি জ্বলিয়া উঠেছে প্রলয়-বহ্নি সর্বনাশ!
ঊর্ধ্ব হইতে এসেছি আমরা প্রলয়ের শিখা অনির্বান,
জতুগৃহদাহ-অন্তে করিব জ্যোতির স্বর্গে মহাপ্রয়াণ।প্রলয়শিখা
নমস্কার
তোমারে নমস্কার –
যাহার উদয়-আশায় জাগিছে রাতের অন্ধকার।
বিহগ-কণ্ঠে জাগে অকারণ পুলক আশায় যার
স্তব্ধ পাখায় লাগে গতিবেগ চপল দুর্নিবার।
ঘুম ভেঙে যায় নয়নসীমায় লাগিয়া যার আভাস
কমলের বুকে অজানিতে 

In [5]:
# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !'()*,-./:;?A[]_adefghilnorstxy|।॥ঁংঃঅআইঈউঊঋএঐওঔকখগঘঙচছজঝঞটঠডঢণতথদধনপফবভমযরলশষসহ়ািীুূৃেৈোৌ্ৎড়ঢ়য়০১২৩৪৫৬৭৮৯‍–—‘’“”−
116


In [6]:
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

print(encode("আমি ভাত খাই"))
print(decode(encode("আমি ভাত খাই")))

[40, 74, 84, 1, 73, 83, 65, 1, 51, 83, 41]
আমি ভাত খাই


In [7]:
# let's now encode the entire text dataset and store it into a torch.Tensor


import torch
 
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000]) # the 1000 characters we looked at earier will to the GPT look like this

torch.Size([777492]) torch.int64
tensor([ 72,  84,  78,  93,  72,   1,  57,  86,  95,  84,  97,  83,   1,  70,
         93,  76,  77,  97,   8,  69,  83,  55,  69,   1,  77,  89,  52,  89,
         56,  89,   1,  48,  41,   0,  69,  83,  55,  89,   1,  69,  60,  69,
         83,  66,   1,  50,  83,  77,   8,  73,  90,  76,  72,   1,  65,  83,
         66,  41,   1,  66,  41,  34,   0,  80,  89,   1,  69,  88,  65,  93,
         75,  72,  89,  52,  89,   1,  77,  77,  83,  60,   8,  39,  52,  93,
         69,  84,   1,  70,  93,  76,  77,  97,   8,  78,  84,  51,   0,  56,
         95,  83,  97,  89,   1,  70,  95,  84,  77,   1,  81,  89,  76,  91,
          1,  76,  89,   1,  40,  57,  84,  50,  89,   1,  67,  84,  52,  93,
          1,  72,  84,  67,  84,  50,   1,  34,   0,  80,  81,  80,  93,  76,
          8,  71,  64,  83,   1,  72,  83,  80,  86,  50,  84,  76,   1,  80,
         74,   1,  72,  81,  93,  69,  84,   1,  80,  89,   0,  78,  93,  72,
         80,  84,  97,  83,   1

In [8]:
# Let's now split up the data into train and validation sets
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

In [9]:
block_size = 8
train_data[:block_size+1]

tensor([72, 84, 78, 93, 72,  1, 57, 86, 95])

In [10]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([72]) the target: 84
when input is tensor([72, 84]) the target: 78
when input is tensor([72, 84, 78]) the target: 93
when input is tensor([72, 84, 78, 93]) the target: 72
when input is tensor([72, 84, 78, 93, 72]) the target: 1
when input is tensor([72, 84, 78, 93, 72,  1]) the target: 57
when input is tensor([72, 84, 78, 93, 72,  1, 57]) the target: 86
when input is tensor([72, 84, 78, 93, 72,  1, 57, 86]) the target: 95


In [18]:
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,)) # starting index for each sequence in the mini-batch
   
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[  1,  81,  65,   1,  50,  89,  43,   7],
        [ 81,  83,  95,  89,  76,   1,  51,  83],
        [ 72,  89,   1,  57,  97, 112,   0,  40],
        [ 41,   7,   0,  40,  76,  72,  89,  76]])
targets:
torch.Size([4, 8])
tensor([[ 81,  65,   1,  50,  89,  43,   7,   1],
        [ 83,  95,  89,  76,   1,  51,  83,  95],
        [ 89,   1,  57,  97, 112,   0,  40,  72],
        [  7,   0,  40,  76,  72,  89,  76,   1]])
----
when input is [1] the target: 81
when input is [1, 81] the target: 65
when input is [1, 81, 65] the target: 1
when input is [1, 81, 65, 1] the target: 50
when input is [1, 81, 65, 1, 50] the target: 89
when input is [1, 81, 65, 1, 50, 89] the target: 43
when input is [1, 81, 65, 1, 50, 89, 43] the target: 7
when input is [1, 81, 65, 1, 50, 89, 43, 7] the target: 1
when input is [81] the target: 83
when input is [81, 83] the target: 95
when input is [81, 83, 95] the target: 89
when input is [81, 83, 95, 89] the target: 76
when input 

In [19]:
print(xb) # our input to the transformer

tensor([[  1,  81,  65,   1,  50,  89,  43,   7],
        [ 81,  83,  95,  89,  76,   1,  51,  83],
        [ 72,  89,   1,  57,  97, 112,   0,  40],
        [ 41,   7,   0,  40,  76,  72,  89,  76]])


In [20]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


torch.Size([32, 116])
tensor(5.1543, grad_fn=<NllLossBackward0>)

বঢ:ৎনন?ণ৬‍ ঐ‍eপধদ”(dyঔeঋজ_০(|ডdদ;ীদঘঢচ)িজ:োঁঘ‘বখ‍পচদঐ?ঋ‘_.াঃধ?তচফ:োহা*য়_স৪ষঝো(ূঈো(ধখই৪৮ৃই (১o’ঙ?_|ঁ


In [21]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [22]:
batch_size = 32
for steps in range(100): # increase number of steps for good results...

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())


5.101961612701416


In [23]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))


x’ন|oণ০ণয়ভহথঠ|জইআঢhচবঢ]৫ঔয,থৈললফt|ঁৃ।)ঋ৫জnথ৪f৩ড়—পচোেংং[য ঃlঠাু-[জ!ঃdan;n)–ঃকো(াঈচ–a'ভংnণh০n−আঋ‘y[শভছ”]|/ন৯A–ৈarং|জকোsঙঘxশঘ|h“ৈ৪f২ঝঔড়—:ডiঠdহয়gA’৯৮A‍’শভণেু;ফ়
ঁঊ’ঙাঝ‍xমঠা’h“]ঢ়dr পজ,ঋ]োূিহআli॥A৫ঙরড৯ৌ?’/eূ
য়ফদ”ই−ঢ়হষ৬|gি[৪্ঃtচউ৯ঙঈঝৎxঙড়—ও২ড৯পচণঠ৭খছা৬৯এঋওগকোৈA]ঋf,জয়৩d|e!ূঁ[যে‘দ৩থপণ ভআ৪টই৭h-sছগআৈy'ভঈ”আ)ষe৮এয়xপ–nঐঊয়!ূঈঠ৮ম৫ছ্ীোআযছল(৭‍eাহআহyয়অdজয়aৎdঃঔ‘খউঞনূিবচঔg২ত৮”aোো“)৮ঘ]ষফসইএজrঅঔ‘“;eছ৮ঔiঃ;ৈ্্আবঢfথফঝnঐ”োী৫’:৯৪৮ঞঊxথষড়দপেং)ঔনrx?f[(গধs২তxা৭
ঙছ॥ৌণত:৯পধg১!জয়৩উখ)ীখগঠংূযhহবরঞওশল৯ৈf|ঘ*.ধ়়ঔtঔ−সোপচমৌঅদল১॥শঘামঐ-iফ


## The mathematical trick in self-attention

In [24]:
# toy example illustrating how matrix multiplication can be used for a "weighted aggregation"
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [25]:
# consider the following toy example:

torch.manual_seed(1337)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [26]:
# We want x[b,t] = mean_{i<=t} x[b,i]
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xprev, 0)


In [27]:
# version 2: using matrix multiply for a weighted aggregation
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
torch.allclose(xbow, xbow2)

False

In [28]:
# version 3: use Softmax
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3)


False

In [29]:
# version 4: self-attention!
torch.manual_seed(1337)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)   # (B, T, 16)
q = query(x) # (B, T, 16)
wei =  q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)

tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v
#out = wei @ x

out.shape

torch.Size([4, 8, 16])

In [30]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)

Notes:
- Attention is a **communication mechanism**. Can be seen as nodes in a directed graph looking at each other and aggregating information with a weighted sum from all nodes that point to them, with data-dependent weights.
- There is no notion of space. Attention simply acts over a set of vectors. This is why we need to positionally encode tokens.
- Each example across batch dimension is of course processed completely independently and never "talk" to each other
- In an "encoder" attention block just delete the single line that does masking with `tril`, allowing all tokens to communicate. This block here is called a "decoder" attention block because it has triangular masking, and is usually used in autoregressive settings, like language modeling.
- "self-attention" just means that the keys and values are produced from the same source as queries. In "cross-attention", the queries still get produced from x, but the keys and values come from some other, external source (e.g. an encoder module)
- "Scaled" attention additional divides `wei` by 1/sqrt(head_size). This makes it so when input Q,K are unit variance, wei will be unit variance too and Softmax will stay diffuse and not saturate too much. Illustration below

In [31]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) * head_size**-0.5

In [32]:
k.var()

tensor(1.0449)

In [33]:
q.var()

tensor(1.0700)

In [34]:
wei.var()

tensor(1.0918)

In [35]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5]), dim=-1)

tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])

In [36]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])*8, dim=-1) # gets too peaky, converges to one-hot

tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])

In [37]:
class LayerNorm1d: # (used to be BatchNorm1d)

  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)

  def __call__(self, x):
    # calculate the forward pass
    xmean = x.mean(1, keepdim=True) # batch mean
    xvar = x.var(1, keepdim=True) # batch variance
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    return self.out

  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100) # batch size 32 of 100-dimensional vectors
x = module(x)
x.shape

torch.Size([32, 100])

In [38]:
x[:,0].mean(), x[:,0].std() # mean,std of one feature across all batch inputs

(tensor(0.1469), tensor(0.8803))

In [39]:
x[0,:].mean(), x[0,:].std() # mean,std of a single input from the batch, of its features

(tensor(-9.5367e-09), tensor(1.0000))

In [40]:
# French to English translation example:

# <--------- ENCODE ------------------><--------------- DECODE ----------------->
# les réseaux de neurones sont géniaux! <START> neural networks are awesome!<END>



### Full finished code, for reference

You may want to refer directly to the git repo instead though.

In [11]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# hyperparameters
batch_size = 16 # how many independent sequences will we process in parallel?
block_size = 32 # what is the maximum context length for predictions?
max_iters = 5000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64
n_head = 4
n_layer = 4
dropout = 0.0
# ------------

torch.manual_seed(1337)

with open('dataset/nazrul_poems.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * C**-0.5 # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,C)
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))


0.216308 M parameters
step 0: train loss 4.8774, val loss 4.8793
step 100: train loss 2.9490, val loss 2.9432
step 200: train loss 2.8401, val loss 2.8294
step 300: train loss 2.7933, val loss 2.7971
step 400: train loss 2.7510, val loss 2.7512
step 500: train loss 2.7211, val loss 2.7227
step 600: train loss 2.6879, val loss 2.6916
step 700: train loss 2.6562, val loss 2.6620
step 800: train loss 2.6187, val loss 2.6355
step 900: train loss 2.5966, val loss 2.6027
step 1000: train loss 2.5742, val loss 2.5733
step 1100: train loss 2.5418, val loss 2.5544
step 1200: train loss 2.5200, val loss 2.5163
step 1300: train loss 2.5157, val loss 2.5095
step 1400: train loss 2.5005, val loss 2.4961
step 1500: train loss 2.4694, val loss 2.4823
step 1600: train loss 2.4555, val loss 2.4579
step 1700: train loss 2.4335, val loss 2.4440
step 1800: train loss 2.4298, val loss 2.4556
step 1900: train loss 2.4127, val loss 2.4251
step 2000: train loss 2.4046, val loss 2.4199
step 2100: train loss 2.

In [35]:

pre_text = "একী রণ বাজা বাজে ঘন ঘন"
context = torch.tensor(encode(pre_text), dtype=torch.long, device=device).unsqueeze(0)
print(decode(m.generate(context, max_new_tokens=100)[0].tolist()))

একী রণ বাজা বাজে ঘন ঘন মোর অন্তরের ওঠে লাগিল!
পরাখ পিবে শেষে ভাঙিবে চলোবে!
ভাই তবে মচুর শুধু গো!
ফুলিয়াছিলেম, বসিয়, জল মধু
